### ISSUE TITLE
Experience Portal caching of Static Resources

### ISSUE THREAD

**Issue by benbatesbrooke** [eschweitzer78/gps-design-systems-lwc#138]
Not an issue specifically with the package, however Salesforce Communities/Experience CDN cache can hold on to previous versions of resources.
As a workaround, we often include UNIX timestamp in resource url to force latest version - not sure if you want to consider this here.
For example, 

`"/sfsites/c/resource/sfGpsDsAuVic/images/logo-primary.png"`

could become

`"/sfsites/c/resource/" + Date.now().toString() + "/sfGpsDsAuVic/images/logo-primary.png"`

**Comment by eschweitzer78** [comment]
Thank you Ben it's a very useful reminder as indeed the CDN can be fairly aggressive in its caching behaviour :-)
Have you spotted a particular area where this would be required? I can think of the "How to" section on the documentation site when one is walked through how to reads a few items from static resources. I'll make a note to address that but let me know if you had anything else in mind.

**Comment by benbatesbrooke** [comment]
It came up for us in testing while playing with primary logo - unlikely to be an issue in Production as they likely won't change often but just thought I'd mention it

**Comment by eschweitzer78** [comment]
That makes sense -- thanks for being that specific.

There are a few areas when the default values are baked in and I'll keep this as a reminder to add the logic you suggest... As a workaround in the meantime, you can always provide your own URL including a timestamp in most if not all places.

**Comment by eschweitzer78** [comment]
@benbatesbrooke I've added a note in the **How To** section in the documentation sites for NSW DS, Service NSW DS and VIC Ripple DS. Hopefully this will be a good reminder. I'll close the issue for now but do not hesitate to add a further comment if you'd like to share other improvement areas.
