### ISSUE TITLE
Include Permission Set in Package

### ISSUE THREAD

**Issue by ghost** [eschweitzer78/gps-design-systems-lwc#141]
### Summary

It might be useful to include a permission set in the package to provide access to portal users to required Apex Classes, for easier implementation. 

### Suggested Solution

Assess permission dependencies for experience cloud users to view/interact with the components and create a generic permission set that is included in the unlocked package.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eschweitzer78** [comment]
Fantastic suggestion Ben!
