### ISSUE TITLE
Header component obscures content in Experience site

### ISSUE THREAD

**Issue by benbatesbrooke** [eschweitzer78/gps-design-systems-lwc#142]
### Summary

When adding the "Site Header" component to the header theme region in Experience Builder, the Header obscures the content region when viewing preview/viewing published site. The behaviour is the same for all combinations of "Is Sticky" and "Hide on Scroll" attributes, which appear to be the only exposed attributes that control the header position.

![image](https://user-images.githubusercontent.com/87344116/236953203-caf223d0-55b3-462c-a2fe-d8605aeb03f4.png)
Header is correctly placed in Builder view. FlexCard in content section is visible

![image](https://user-images.githubusercontent.com/87344116/236953287-c5361cd3-b8e5-4858-90df-e28339d501ff.png)
When previewing, the content flex card is obscured behind the Header

### Salesforce Org Type

Developer Edition Org

### Steps To Reproduce

1. Create new Aura Experience Site
2. Update theme settings as per documentation
3. Add Site Header component to header region and configure as per documentation
4. Add Component to Content region (confirmed same behaviour with FlexCard and standard HTML component)

### Current Behavior

The header floats above the content and obscures the content

### Expected Behavior

The header should be locked above the content section

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eschweitzer78** [comment]
Hi Ben, it looks like you are using the default page content layout. The only supported page content layout is the Flexible Layout, it's something I added recently in the how to instructions.

You may need to create a variation of your page to be able to pick it. Then, make the new variation the default. I reckon that once this is done, you should see that there is enough padding to allow for the header to appear above the content. 

Let me know how this goes.

**Comment by benbatesbrooke** [comment]
Perfect, thanks @eschweitzer78. I was also missing the head markup for the customer service theme, now working as expected!
