### ISSUE TITLE
sfGpsDsAuNswFormSelectOsN component not working in Spring 24 sandbox

### ISSUE THREAD

**Issue by rajeshkeswani** [eschweitzer78/gps-design-systems-lwc#280]
### Summary

sfGpsDsAuNswFormSelectOsN component not working in Spring 24 sandbox

### Salesforce Org Type

Sandbox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eschweitzer78** [comment]
Hi @rajeshkeswani. I'll have a look as I have a preview sandbox available -- is there any more specific info you can share?

**Comment by rajeshkeswani** [comment]
@eschweitzer78 thanks for your prompt reply.
I see dropdown is not coming when clicked on combobox

![MicrosoftTeams-image (124)](https://github.com/eschweitzer78/gps-design-systems-lwc/assets/143563220/67c3414d-eefa-41a9-bb07-5ad95c2c6e37)

**Comment by eschweitzer78** [comment]
Hi Rajesh, it looks like Omnistudio 248 introduces a breaking change on the combobox class that's used in the Select widget (well, breaking if you do change the HTML template or look at the 246 template):

- in 248 there is event handling on the input for blur, click, keydown or keyup
- whereas in 246 it was blur, mouseup, keydown, keyup

As the event handle actively checks the event type, mouseup no longer matches the new requirement for click. I'll modify the template used in the library to add click as well, the excess event should be discarded (click discarded in 246, mouseup discarded in 248).

**Comment by eschweitzer78** [comment]
This workaround/fix leads to the right outcome in my preview sandbox, so I'll start a build for that momentarily. Thanks for reporting -- it does really help. Kindly share any other concern you spot with omnistudio 248.

**Comment by deniskrizanovic** [comment]
WooHoo!

**Comment by rajeshkeswani** [comment]
@eschweitzer78 : Thanks for your quick help here! I will close the bug once fixed in REV sandbox.
