### ISSUE TITLE
Select form field background repeating an icon

### ISSUE THREAD

**Issue by stoffi-dev** [eschweitzer78/gps-design-systems-lwc#301]
### Summary

When the form validation fails on a select field. The background of the select field is a repeated icon image. See the image.

![image (5)](https://github.com/eschweitzer78/gps-design-systems-lwc/assets/40679021/a7ef22be-398f-45c5-84d3-0aac842f6fed)

### Salesforce Org Type

Sandbox

## Setup
OmniStudio version: 248.1
In a Salesforce community with the NSW Gov template selected.

Omni form component in use on page: public/ContactUs/English (lwc export [publicContactUsEnglish.zip](https://github.com/eschweitzer78/gps-design-systems-lwc/files/14133169/publicContactUsEnglish.zip) ) with builder configuration:
``` 
layout: lightning
inline: false
inlineLabel: Launch undefined/undefined
inlineVariant: brand
Record Id: {!recordId}
Region Width: LARGE
dir: ltr
```
Utilising the omniscript configuration:
```
"elementTypeToLwcTemplateMapping": {
    "Step": "sfGpsDsAuNswFormStepOsN",
    "Email": "sfGpsDsAuNswFormEmailOsN",
    "Telephone": "sfGpsDsAuNswFormTextOsN",
    "Text": "sfGpsDsAuNswFormTextOsN",
    "Select": "sfGpsDsAuNswFormSelectOsN",
    "Text Area": "sfGpsDsAuNswFormTextareaOsN",
    "Radio": "sfGpsDsAuNswFormRadioOsN",
    "Checkbox": "sfGpsDsAuNswFormCheckboxOsN",
    "Button": "sfGpsDsAuNswButtonOs",
    "Currency": "sfGpsDsAuNswFormCurrencyOsN",
    "Date": "sfGpsDsAuNswFormDateOsN",
    "Date/Time (Local)": "sfGpsDsAuNswFormDateTimeOsN",
    "Disclosure": "sfGpsDsAuNswFormDisclosureOsN",
    "File": "sfGpsDsAuNswFormFileOsN",
    "Multi-select": "sfGpsDsAuNswFormMultiselectOsN",
    "Number": "sfGpsDsAuNswFormNumberOsN",
    "Password": "sfGpsDsAuNswFormPasswordOsN",
    "StepChart": "sfGpsDsAuNswFormStepChartOsN",
    "Time": "sfGpsDsAuNswFormTimeOsN",
    "Type Ahead": "sfGpsDsAuNswFormTypeaheadOsN",
    "URL": "sfGpsDsAuNswFormUrlOsN"
  }
```

## Steps to produce
1. Navigate to community page where the component has been placed. (Can be in preview mode through builder).

2. Cause a validation error on the 'How can we help' field, by either not selecting a value and trying to submit the form. Or, select a valid value then reselect --Clear--.

3. Once validation error has flagged on the field with the visible red border, attempt to reselect a valid value again and the background of the drop down will be the chevron icon repeated.

### Current Behavior

When the 'How can we help' field remains unselected in preview mode. The form validation error flags to require input. On opening the 'How can we help' field to select a value, the background of the select field has a repeated background image of the chevron icon.

After a value has been selected and the validation passes, the background returns to normal white without issue.

### Expected Behavior

Whether the select field flags validation or not, the background should remain the same and not have a repeated icon image.

### Relevant Log Output

```shell
No log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eschweitzer78** [comment]
Thank you. I have successful reproduced and a fix is on the way!

**Comment by eschweitzer78** [comment]
@stoffi-dev here is the visuals of version that's fixed. A build is underway, you should find a new sandbox package on the README page within 60 to 90 minutes.
Let me know if that helps after updating; if so we'll close the bug and I'll promote for use in prod.

Thanks again for reporting.

**Comment by eschweitzer78** [comment]
<img width="1222" alt="image" src="https://github.com/eschweitzer78/gps-design-systems-lwc/assets/20468027/840514c1-f051-4336-b6af-057bde59ca76">

**Comment by eschweitzer78** [comment]
<img width="1182" alt="image" src="https://github.com/eschweitzer78/gps-design-systems-lwc/assets/20468027/3bc1fa8b-0553-4ba6-aff9-74ecd2adf2c1">

**Comment by stoffi-dev** [comment]
This looks great! thanks @eschweitzer78 Ill give it a test when it comes through.
