### ISSUE TITLE
Unable to VIC unlocked package in Production

### ISSUE THREAD

**Issue by batesbw** [eschweitzer78/gps-design-systems-lwc#316]
### Summary

Unable to install Vic unlocked package into Prod org

### Salesforce Org Type

Production Org

### Steps To Reproduce

Follow instructions on Readme to install into production

### Current Behavior

he component included in step 5 on the below screenshot contains the theme. I installed the pre-requisite component in Step 2, but unable to finish the step 5.
 
![image](https://github.com/eschweitzer78/gps-design-systems-lwc/assets/8152754/d7b31538-0b90-4599-855c-dbd256a2a7a3)

 
I could not install the package linked from Step 5 due to errors encountered. I resolved the 2 errors highlighted in GREEN (manually cloned the repo and pushed only the missing apex/lwc) below but I cannot resolve the first one highlighted in red since it is missing from the git repository. There is an LCW with almost similar name “sfGpsDsOmniHelpersOsN” but haven’t tried this one yet as it seems to contain a function not visibly relevant with how the dependent component is trying to call it, we can take a shot though.. or maybe Jase has this component on your previous project, something we can try to pull?

![image](https://github.com/eschweitzer78/gps-design-systems-lwc/assets/8152754/58ead4ec-e326-45a4-8e44-ae8cb7c813b5)

### Expected Behavior

Installation is correct

### Relevant Log Output

```shell
See image in current behaviour
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eschweitzer78** [comment]
Hi Benjamin and thank you so much for reporting the issue. Upon closer inspection, it looks like it may be linked to a faulty build logic which has been corrected since. As a result, I have promoted the current sandbox packages for production use.

Please try https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5j000000dzFEAAY for the VIC Ripple 1 Design System and let me know how you're doing.

**Comment by batesbw** [comment]
Thanks so much for the quick turnaround Emmanuel, i'll forward to the team and get back to you.
Cheers,
Ben

**Comment by eschweitzer78** [comment]
FYI I edited the original response to add the following -- I am not sure this was reflected in the automated email you may have received:

> Kindly note that sfGpsDs is no longer a prerequisite for this version. If you have sfGpsDs installed in production, please refer to https://github.com/eschweitzer78/gps-design-systems-lwc?tab=readme-ov-file#moving-away-from-separate-base-and-design-system-libraries

**Comment by eschweitzer78** [comment]
Hi @batesbw may I close the issue?

**Comment by batesbw** [comment]
Yes, apologies!
