### ISSUE TITLE
Unable to upgrade the "Salesforce Global Public Sector AU NSW Design System 2024.05.21.2000"

### ISSUE THREAD

**Issue by rajeshkeswani** [eschweitzer78/gps-design-systems-lwc#335]
### Summary

Not able to upgrade the package getting below error :

Problem:

1. LightningComponentBundle(sfGpsDsAuNswMarkdownElementCommOs) lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Page from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Default from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove targetConfigs because the targetConfig for lightningCommunity__Default is needed. This component is part of a managed package.
sfGpsDsAuNswMarkdownElementCommOs: lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Page from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Default from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove targetConfigs because the targetConfig for lightningCommunity__Default is needed. This component is part of a managed package.

2. LightningComponentBundle(sfGpsDsAuNswMarkdownElementCommOs) lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Page from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Default from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove targetConfigs because the targetConfig for lightningCommunity__Default is needed. This component is part of a managed package.
sfGpsDsAuNswMarkdownElementCommOs: lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Page from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Default from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove targetConfigs because the targetConfig for lightningCommunity__Default is needed. This component is part of a managed package.

3. LightningComponentBundle(sfGpsDsAuNswMarkdownElementCommOs) lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Page from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Default from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove targetConfigs because the targetConfig for lightningCommunity__Default is needed. This component is part of a managed package.
sfGpsDsAuNswMarkdownElementCommOs: lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Page from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove the lightningCommunity__Default from targets. This component is part of a managed package.
lwc/sfGpsDsAuNswMarkdownElementCommOs/sfGpsDsAuNswMarkdownElementCommOs.js-meta.xml: You can't remove targetConfigs because the targetConfig for lightningCommunity__Default is needed. This component is part of a managed package.

### Salesforce Org Type

Sandbox

### Steps To Reproduce

1. upgrade sfGpsDs to a version we packaged with all artefacts marked as deprecated -- this must be done on the command line using sfdx package install --package=04t5j000000dnflAAA --upgrade-type=DeprecateOnly ,
2. upgrade the jurisdiction's design system library to a version with the former sfGpsDs dependencies included using one of the links above,
3. uninstall sfGpsDs now that all deprecated files have been absorbed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eschweitzer78** [comment]
Hello Rajesh and thank you for reaching out. I appreciate you taking the time to describe the issue. We indeed had a slight packaging incident in the past when we let a community setting bleed into a component generated for OmniStudio use when that should not be required.

My best guess is that you haven't use this component in a custom LWC configuration on any Omniscript as it's fairly new and it's not been spruiked much. 

In that case the best course of action is two use `sfdx` and potentially Visual Studio Code if you have it in your setup and do the following:

1. Download the offending LWC `sfGpsDsAuNswMarkdownElementCommOs` in a new sfdx project.  Then use the SFDX contextual menu to Delete this LWC from the project and org.
2. Install the new version of the NSW DS library as you were trying to 

The issue should then be solved with the correct, most recent version of `sfGpsDsAuNswMarkdownElementCommOs` installed.

Let me know if you do not have Visual Code Studio. I will let you know the exact sfdx commands to run on the command line as an alternative.

Kindly let me know how that goes.

**Comment by rajeshkeswani** [comment]
Thanks Emmanuel for your prompt response on the issue. I am able to upgrade the package after following your instructions hence closing the issue.
Thank you !
