### ISSUE TITLE
Support for Save and Cancel buttons in EditBlock element

### ISSUE THREAD

**Issue by jeirrazabal** [eschweitzer78/gps-design-systems-lwc#375]
Can we align the "Save" and "Cancel" EditBlock buttons look and feel with the NSW design so it is consistent within the whole site?

<img width="1296" alt="Screenshot 2024-07-18 at 9 41 36 PM" src="https://github.com/user-attachments/assets/83b15b89-b94c-40a3-a14e-1cb3567ae594">
<img width="1377" alt="Screenshot 2024-07-18 at 9 42 15 PM" src="https://github.com/user-attachments/assets/c58f6c38-bf9b-4076-a635-0e7c4a66c0f2">
<img width="1377" alt="Screenshot 2024-07-18 at 9 43 13 PM" src="https://github.com/user-attachments/assets/a45df3e7-90ca-478e-a683-83e6f851fb7e">
 
Thank you!

**Comment by eschweitzer78** [comment]
Hi @jeirrazabal I had a look and it seems like this requires more than just styling the buttons. Multiple characteristics of the edit block would benefit from adjusted styling when aligning to the NSW DS and the inline mode you've been using is just the tip of the iceberg.

This will require more time than I have available at the moment to do thoroughly and I hence must delay support for this complex element and tag it as considered.

But in the meantime I have added enough in the stylesheets to deal with the cancel and save buttons in inline edit mode. I will push the update some time before start of business tomorrow.
